### ISSUE TITLE
Initial Project setup

### ISSUE THREAD

**Issue by otarza** [bitcamp-ge/twitter-clone-py-t1#1]
- [x] Create Python virtual environment
- [x] Create Django project
- [x] Install DRF
- [x] Configure admin & users
- [x] Configure DRF authentication
- [x] Configure CORS
- [x] Configure and implement /users endpoint to be able to create new users.
- [x] Run migrations
- [x] Create `.gitignore` for Django project
- [x] Create requirements.txt
- [x] Create a README.md file which describes how to setup this project.
- [x] Create super user

**Comment by nodarisvanidze88** [comment]
ვფიქრობ რომ models.py დაგვჭირდება სადაც იუზერების ინიციალიზაციას გააკეთებ
