### ISSUE TITLE
Create Hashtag model

### ISSUE THREAD

**Issue by otarza** [bitcamp-ge/twitter-clone-py-t1#10]

**Comment by zoiatsitsilashvili** [comment]
- [ ]  Hashtag Model: Post მოდელის მსგავსად, თქვენ შექმნით Python კლასს models.py ფაილში ჰეშთეგის სტრუქტურის წარმოსადგენად. სახელის ველი შეინახავს ჰეშთეგის ტექსტს.

- [ ] Run - python manage.py makemigrations

- [ ] Run Django migrations: python manage.py migrate

- [ ] შევქმნათ Serializers: ჩვენი აპლიკაციის serializers.py ფაილში, განსაზღვრავთ სერიალიზატორებს Hashtag-ის მოდელებისთვის
