### ISSUE TITLE
Create Search view using filtration via DRF

### ISSUE THREAD

**Issue by otarza** [bitcamp-ge/twitter-clone-py-t1#13]

**Comment by Sabakhupenia** [comment]
- [ ] 1. Create a Serializer: creating a serializer to handle the input data and output data
- [ ] 2. Define filter: Install django_filters using: pip install django-filters Define filters using django-filter for each type of content you want to search for. 
- [ ] 3. Add URL Routes: Add URL routes for each search view in your urls.py:
