### ISSUE TITLE
Create Post model

### ISSUE THREAD

**Issue by otarza** [bitcamp-ge/twitter-clone-py-t1#2]

**Comment by zoiatsitsilashvili** [comment]
- [ ] Post Model - განვსაზღვროთ პოსტის მოდელის კლასი აპლიკაციის  models.py ფაილში. ეს კლასი მოიცავც შემდეგ ველებს, როგორიცაა ავტორი, სათაური, შინაარსი და ჰეშთეგები.   

- [ ]  ForeignKey ველს გამოვიყენებთ მომხმარებლის მოდელთან ურთიერთობის დასამყარებლად, რომელიც წარმოადგენს პოსტის ავტორს. ManyToManyField ველი გამოიყენება Hashtag-ის მოდელთან მრავალი-მრავალზე ურთიერთობის დასამყარებლად, რაც საშუალებას აძლევს მრავალ ჰეშთეგს ასოცირდეს ერთ პოსტთან. 

- [ ] შემდეგ გავუშვებთ ბრძანებას - python manage.py makemigrations

- [ ] Run Django migrations: python manage.py migrate

- [ ]  შევქმნათ Serializers: ჩვენი აპლიკაციის serializers.py ფაილში,  განსაზღვრავთ სერიალიზატორებს Post-ის მოდელებისთვის

- [ ]  Views  განსაზღვრა: ჩვენი აპის views.py ფაილში  შევქმნით Views ფუნქციებს ან კლასებს, რომლებიც ამუშავებენ პოსტებთან დაკავშირებულ სხვადასხვა მოქმედებებს. ეს ქმედებები შეიძლება მოიცავდეს ყველა პოსტის ჩამონათვალს, ახალი პოსტების შექმნას, პოსტების განახლებას და პოსტების წაშლას. 

- [ ]  URLs:  urls.py ფაილში  დავაკონფიგურირებთ URL-ებს, რომლებიც შეესაბამებიან თქვენ მიერ განსაზღვრულ  Views.
