### ISSUE TITLE
Create Comment model

### ISSUE THREAD

**Issue by otarza** [bitcamp-ge/twitter-clone-py-t1#6]

**Comment by Sabakhupenia** [comment]
- [ ] 1. List Comments for Content: Retrieve a list of comments associated with a specific content.

- [ ] 2. Create Comment: Description: Create a new comment for a content item.

- [ ] 3. Retrieve Comment: Retrieve details of a specific comment.

- [ ] 4. Update Comment: Update the content of a specific comment.

- [ ] 5. Delete Comment: Delete a specific comment.

**Comment by Sabakhupenia** [comment]
#13
